// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `empty`, `err`, `profile`, `profiles`, `run`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `clone`, `clone`, `eq`, `eq`, `fmt`, `fmt`, `from`

DeviceProfileOperationResult listPersistedDeviceProfiles({
  required String databasePath,
  required String playerId,
}) => RustLib.instance.api.crateApiDeviceProfilesListPersistedDeviceProfiles(
  databasePath: databasePath,
  playerId: playerId,
);

DeviceProfileOperationResult createPersistedDeviceProfile({
  required String databasePath,
  required String playerId,
  required String profileJson,
}) => RustLib.instance.api.crateApiDeviceProfilesCreatePersistedDeviceProfile(
  databasePath: databasePath,
  playerId: playerId,
  profileJson: profileJson,
);

DeviceProfileOperationResult updatePersistedDeviceProfile({
  required String databasePath,
  required String playerId,
  required String profileJson,
}) => RustLib.instance.api.crateApiDeviceProfilesUpdatePersistedDeviceProfile(
  databasePath: databasePath,
  playerId: playerId,
  profileJson: profileJson,
);

DeviceProfileOperationResult updateDeviceProfileSettings({
  required String databasePath,
  required String playerId,
  required String deviceProfileId,
  required double inputOffsetMs,
  required VelocityCurveDto velocityCurve,
}) => RustLib.instance.api.crateApiDeviceProfilesUpdateDeviceProfileSettings(
  databasePath: databasePath,
  playerId: playerId,
  deviceProfileId: deviceProfileId,
  inputOffsetMs: inputOffsetMs,
  velocityCurve: velocityCurve,
);

DeviceProfileOperationResult deletePersistedDeviceProfile({
  required String databasePath,
  required String playerId,
  required String deviceProfileId,
}) => RustLib.instance.api.crateApiDeviceProfilesDeletePersistedDeviceProfile(
  databasePath: databasePath,
  playerId: playerId,
  deviceProfileId: deviceProfileId,
);

DeviceProfileOperationResult setLastUsedDeviceProfile({
  required String databasePath,
  required String playerId,
  required String deviceProfileId,
}) => RustLib.instance.api.crateApiDeviceProfilesSetLastUsedDeviceProfile(
  databasePath: databasePath,
  playerId: playerId,
  deviceProfileId: deviceProfileId,
);

DeviceProfileOperationResult lastUsedDeviceProfileForDevice({
  required String databasePath,
  required String playerId,
  String? vendorName,
  String? modelName,
  String? platformId,
}) => RustLib.instance.api.crateApiDeviceProfilesLastUsedDeviceProfileForDevice(
  databasePath: databasePath,
  playerId: playerId,
  vendorName: vendorName,
  modelName: modelName,
  platformId: platformId,
);

class DeviceProfileOperationResult {
  final String? profileJson;
  final List<String> profilesJson;
  final String? error;

  const DeviceProfileOperationResult({
    this.profileJson,
    required this.profilesJson,
    this.error,
  });

  @override
  int get hashCode =>
      profileJson.hashCode ^ profilesJson.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DeviceProfileOperationResult &&
          runtimeType == other.runtimeType &&
          profileJson == other.profileJson &&
          profilesJson == other.profilesJson &&
          error == other.error;
}

enum VelocityCurveDto { linear, soft, hard }
