// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `attempt`, `attempts`, `err`, `run`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `clone`, `eq`, `fmt`

PracticeAttemptOperationResult recordPracticeAttempt({
  required String databasePath,
  required String summaryJson,
  required String contextJson,
}) => RustLib.instance.api.crateApiPracticeAttemptsRecordPracticeAttempt(
  databasePath: databasePath,
  summaryJson: summaryJson,
  contextJson: contextJson,
);

PracticeAttemptOperationResult listPracticeAttempts({
  required String databasePath,
  required String playerId,
  String? lessonId,
  String? courseId,
  String? startedAtUtcFrom,
  String? startedAtUtcTo,
}) => RustLib.instance.api.crateApiPracticeAttemptsListPracticeAttempts(
  databasePath: databasePath,
  playerId: playerId,
  lessonId: lessonId,
  courseId: courseId,
  startedAtUtcFrom: startedAtUtcFrom,
  startedAtUtcTo: startedAtUtcTo,
);

class PracticeAttemptOperationResult {
  final String? attemptJson;
  final List<String> attemptsJson;
  final String? error;

  const PracticeAttemptOperationResult({
    this.attemptJson,
    required this.attemptsJson,
    this.error,
  });

  @override
  int get hashCode =>
      attemptJson.hashCode ^ attemptsJson.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PracticeAttemptOperationResult &&
          runtimeType == other.runtimeType &&
          attemptJson == other.attemptJson &&
          attemptsJson == other.attemptsJson &&
          error == other.error;
}
