// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `as_str`, `drain_runtime_events`, `empty_events_json`, `from_result`, `grade_as_str`, `start_session_impl`, `submit_midi_event`, `timeline_json`, `validate_channel`, `validate_velocity`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `EngineEventDto`, `PracticeRuntimeTimelineDto`, `TimelineLaneDto`, `TimelineNoteDto`, `TimelineSectionDto`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`

PlatformInt64 practiceRuntimeClockNs() =>
    RustLib.instance.api.crateApiPracticeRuntimePracticeRuntimeClockNs();

PracticeRuntimeStartResult startPracticeRuntimeSession({
  required PracticeRuntimeStartRequest request,
}) => RustLib.instance.api.crateApiPracticeRuntimeStartPracticeRuntimeSession(
  request: request,
);

PracticeRuntimeOperationResult practiceRuntimeSubmitTouchHit({
  required int sessionId,
  required String laneId,
  required int velocity,
  required PlatformInt64 timestampNs,
}) => RustLib.instance.api.crateApiPracticeRuntimePracticeRuntimeSubmitTouchHit(
  sessionId: sessionId,
  laneId: laneId,
  velocity: velocity,
  timestampNs: timestampNs,
);

PracticeRuntimeOperationResult practiceRuntimeSubmitMidiNoteOn({
  required int sessionId,
  required int channel,
  required int note,
  required int velocity,
  required PlatformInt64 timestampNs,
}) =>
    RustLib.instance.api.crateApiPracticeRuntimePracticeRuntimeSubmitMidiNoteOn(
      sessionId: sessionId,
      channel: channel,
      note: note,
      velocity: velocity,
      timestampNs: timestampNs,
    );

PracticeRuntimeOperationResult practiceRuntimeSubmitMidiControlChange({
  required int sessionId,
  required int channel,
  required int controller,
  required int value,
  required PlatformInt64 timestampNs,
}) => RustLib.instance.api
    .crateApiPracticeRuntimePracticeRuntimeSubmitMidiControlChange(
      sessionId: sessionId,
      channel: channel,
      controller: controller,
      value: value,
      timestampNs: timestampNs,
    );

PracticeRuntimeOperationResult practiceRuntimeTick({
  required int sessionId,
  required PlatformInt64 nowNs,
}) => RustLib.instance.api.crateApiPracticeRuntimePracticeRuntimeTick(
  sessionId: sessionId,
  nowNs: nowNs,
);

PracticeRuntimeOperationResult practiceRuntimeDrainEvents({
  required int sessionId,
}) => RustLib.instance.api.crateApiPracticeRuntimePracticeRuntimeDrainEvents(
  sessionId: sessionId,
);

PracticeRuntimeOperationResult practiceRuntimePause({required int sessionId}) =>
    RustLib.instance.api.crateApiPracticeRuntimePracticeRuntimePause(
      sessionId: sessionId,
    );

PracticeRuntimeOperationResult practiceRuntimeResume({
  required int sessionId,
}) => RustLib.instance.api.crateApiPracticeRuntimePracticeRuntimeResume(
  sessionId: sessionId,
);

PracticeRuntimeStopResult practiceRuntimeStop({required int sessionId}) =>
    RustLib.instance.api.crateApiPracticeRuntimePracticeRuntimeStop(
      sessionId: sessionId,
    );

PracticeRuntimeOperationResult practiceRuntimeDispose({
  required int sessionId,
}) => RustLib.instance.api.crateApiPracticeRuntimePracticeRuntimeDispose(
  sessionId: sessionId,
);

enum PracticeRuntimeModeDto { practice, play, courseGate }

class PracticeRuntimeOperationResult {
  final String? eventsJson;
  final String? error;

  const PracticeRuntimeOperationResult({this.eventsJson, this.error});

  @override
  int get hashCode => eventsJson.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PracticeRuntimeOperationResult &&
          runtimeType == other.runtimeType &&
          eventsJson == other.eventsJson &&
          error == other.error;
}

class PracticeRuntimeStartRequest {
  final String lessonJson;
  final String layoutJson;
  final String scoringProfileJson;
  final String? deviceProfileJson;
  final PracticeRuntimeModeDto mode;
  final double bpm;
  final PlatformInt64 startTimeNs;
  final PlatformInt64 lookaheadMs;

  const PracticeRuntimeStartRequest({
    required this.lessonJson,
    required this.layoutJson,
    required this.scoringProfileJson,
    this.deviceProfileJson,
    required this.mode,
    required this.bpm,
    required this.startTimeNs,
    required this.lookaheadMs,
  });

  @override
  int get hashCode =>
      lessonJson.hashCode ^
      layoutJson.hashCode ^
      scoringProfileJson.hashCode ^
      deviceProfileJson.hashCode ^
      mode.hashCode ^
      bpm.hashCode ^
      startTimeNs.hashCode ^
      lookaheadMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PracticeRuntimeStartRequest &&
          runtimeType == other.runtimeType &&
          lessonJson == other.lessonJson &&
          layoutJson == other.layoutJson &&
          scoringProfileJson == other.scoringProfileJson &&
          deviceProfileJson == other.deviceProfileJson &&
          mode == other.mode &&
          bpm == other.bpm &&
          startTimeNs == other.startTimeNs &&
          lookaheadMs == other.lookaheadMs;
}

class PracticeRuntimeStartResult {
  final int? sessionId;
  final String? timelineJson;
  final String? error;

  const PracticeRuntimeStartResult({
    this.sessionId,
    this.timelineJson,
    this.error,
  });

  @override
  int get hashCode =>
      sessionId.hashCode ^ timelineJson.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PracticeRuntimeStartResult &&
          runtimeType == other.runtimeType &&
          sessionId == other.sessionId &&
          timelineJson == other.timelineJson &&
          error == other.error;
}

class PracticeRuntimeStopResult {
  final String? summaryJson;
  final String? eventsJson;
  final String? error;

  const PracticeRuntimeStopResult({
    this.summaryJson,
    this.eventsJson,
    this.error,
  });

  @override
  int get hashCode =>
      summaryJson.hashCode ^ eventsJson.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PracticeRuntimeStopResult &&
          runtimeType == other.runtimeType &&
          summaryJson == other.summaryJson &&
          eventsJson == other.eventsJson &&
          error == other.error;
}
