// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `err`, `snapshot`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `clone`, `eq`, `fmt`

PracticeHabitOperationResult loadPracticeHabitSnapshot({
  required String databasePath,
  required String playerId,
  required String todayLocalDayKey,
}) => RustLib.instance.api.crateApiPracticeHabitsLoadPracticeHabitSnapshot(
  databasePath: databasePath,
  playerId: playerId,
  todayLocalDayKey: todayLocalDayKey,
);

class PracticeHabitOperationResult {
  final String? snapshotJson;
  final String? error;

  const PracticeHabitOperationResult({this.snapshotJson, this.error});

  @override
  int get hashCode => snapshotJson.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PracticeHabitOperationResult &&
          runtimeType == other.runtimeType &&
          snapshotJson == other.snapshotJson &&
          error == other.error;
}
