// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `err`, `ok`, `run`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`, `from`, `from`, `from`

LocalProfileOperationResult localProfileState({required String databasePath}) =>
    RustLib.instance.api.crateApiProfilesLocalProfileState(
      databasePath: databasePath,
    );

LocalProfileOperationResult createLocalProfile({
  required String databasePath,
  required String name,
  String? avatar,
  required ProfileExperienceLevelDto experienceLevel,
}) => RustLib.instance.api.crateApiProfilesCreateLocalProfile(
  databasePath: databasePath,
  name: name,
  avatar: avatar,
  experienceLevel: experienceLevel,
);

LocalProfileOperationResult setActiveLocalProfile({
  required String databasePath,
  required String profileId,
}) => RustLib.instance.api.crateApiProfilesSetActiveLocalProfile(
  databasePath: databasePath,
  profileId: profileId,
);

LocalProfileOperationResult updateLocalProfilePreferredView({
  required String databasePath,
  required String profileId,
  required ProfilePracticeViewDto preferredView,
}) => RustLib.instance.api.crateApiProfilesUpdateLocalProfilePreferredView(
  databasePath: databasePath,
  profileId: profileId,
  preferredView: preferredView,
);

LocalProfileOperationResult updatePlayerProfileName({
  required String databasePath,
  required String profileId,
  required String name,
}) => RustLib.instance.api.crateApiProfilesUpdatePlayerProfileName(
  databasePath: databasePath,
  profileId: profileId,
  name: name,
);

LocalProfileOperationResult deleteLocalProfile({
  required String databasePath,
  required String profileId,
}) => RustLib.instance.api.crateApiProfilesDeleteLocalProfile(
  databasePath: databasePath,
  profileId: profileId,
);

class LocalProfileOperationResult {
  final LocalProfileStateDto? state;
  final String? error;

  const LocalProfileOperationResult({this.state, this.error});

  @override
  int get hashCode => state.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LocalProfileOperationResult &&
          runtimeType == other.runtimeType &&
          state == other.state &&
          error == other.error;
}

class LocalProfileStateDto {
  final List<PlayerProfileDto> profiles;
  final String? activeProfileId;

  const LocalProfileStateDto({required this.profiles, this.activeProfileId});

  @override
  int get hashCode => profiles.hashCode ^ activeProfileId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LocalProfileStateDto &&
          runtimeType == other.runtimeType &&
          profiles == other.profiles &&
          activeProfileId == other.activeProfileId;
}

class PlayerProfileDto {
  final String id;
  final String name;
  final String? avatar;
  final ProfileExperienceLevelDto experienceLevel;
  final ProfilePracticeViewDto preferredView;
  final String createdAt;
  final String updatedAt;

  const PlayerProfileDto({
    required this.id,
    required this.name,
    this.avatar,
    required this.experienceLevel,
    required this.preferredView,
    required this.createdAt,
    required this.updatedAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      avatar.hashCode ^
      experienceLevel.hashCode ^
      preferredView.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PlayerProfileDto &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          avatar == other.avatar &&
          experienceLevel == other.experienceLevel &&
          preferredView == other.preferredView &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt;
}

enum ProfileExperienceLevelDto { beginner, intermediate, teacher }

enum ProfilePracticeViewDto { noteHighway, notation }
