// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `err`, `run`, `settings`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `clone`, `eq`, `fmt`

SettingsOperationResult loadSettingsSnapshot({
  required String databasePath,
  required String playerId,
}) => RustLib.instance.api.crateApiSettingsLoadSettingsSnapshot(
  databasePath: databasePath,
  playerId: playerId,
);

SettingsOperationResult updateAppSettings({
  required String databasePath,
  required String settingsJson,
}) => RustLib.instance.api.crateApiSettingsUpdateAppSettings(
  databasePath: databasePath,
  settingsJson: settingsJson,
);

SettingsOperationResult updateProfileSettings({
  required String databasePath,
  required String playerId,
  required String settingsUpdateJson,
}) => RustLib.instance.api.crateApiSettingsUpdateProfileSettings(
  databasePath: databasePath,
  playerId: playerId,
  settingsUpdateJson: settingsUpdateJson,
);

class SettingsOperationResult {
  final String? settingsJson;
  final String? error;

  const SettingsOperationResult({this.settingsJson, this.error});

  @override
  int get hashCode => settingsJson.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SettingsOperationResult &&
          runtimeType == other.runtimeType &&
          settingsJson == other.settingsJson &&
          error == other.error;
}
