// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `monotonic_now_ns`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `clone`, `eq`, `fmt`

String greet({required String name}) =>
    RustLib.instance.api.crateApiSimpleGreet(name: name);

PlatformInt64 phase0LatencyClockNs() =>
    RustLib.instance.api.crateApiSimplePhase0LatencyClockNs();

Phase0LatencyRustResult measurePhase0LatencyHit({
  required String laneId,
  required int velocity,
  required PlatformInt64 nativeTimestampNs,
}) => RustLib.instance.api.crateApiSimpleMeasurePhase0LatencyHit(
  laneId: laneId,
  velocity: velocity,
  nativeTimestampNs: nativeTimestampNs,
);

class Phase0LatencyRustResult {
  final PlatformInt64 nativeTimestampNs;
  final PlatformInt64 rustEntryNs;
  final PlatformInt64 rustExitNs;
  final int engineEventCount;

  const Phase0LatencyRustResult({
    required this.nativeTimestampNs,
    required this.rustEntryNs,
    required this.rustExitNs,
    required this.engineEventCount,
  });

  @override
  int get hashCode =>
      nativeTimestampNs.hashCode ^
      rustEntryNs.hashCode ^
      rustExitNs.hashCode ^
      engineEventCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Phase0LatencyRustResult &&
          runtimeType == other.runtimeType &&
          nativeTimestampNs == other.nativeTimestampNs &&
          rustEntryNs == other.rustEntryNs &&
          rustExitNs == other.rustExitNs &&
          engineEventCount == other.engineEventCount;
}
